Update Serilog.Sinks.SQLite.csproj
BugFix for Android Plattform (Xamarin): Included missing SQLitePCLRaw.core Nuget Reference like discussed here:
https://stackoverflow.com/questions/50746465/how-do-i-call-sqlitepcl-batteries-init

This fixed following error:
System.Exception: 'You need to call SQLitePCL.raw.SetProvider(). If you are using a bundle package, this is done by calling SQLitePCL.Batteries.Init().'